---
- name: Ansible play to provision bastion machine
  hosts: rhods_bastion
  vars_files:
    - user_vars.yml
  tasks: 
    - name: Check all variables are populated
      ansible.builtin.fail:
        msg: All variables in rhods_bastion.yml should be populated.
      when: (quay_auth_token == None or quay_auth_token is not defined) or (github_access_token == None or github_access_token is not defined) or (github_account == None or github_account is not defined) or (s3_secret == None or s3_secret is not defined)

    - name: Clone rh-emea-sa repository
      ansible.builtin.git:
        repo: https://github.com/rh-emea-sa/industrial-edge.git
        dest: /home/lab-user/industrial-edge
        version: ml-ci-cd

    - name: Populate values-secret.yml file in {{ ansible_user }} home
      ansible.builtin.template:
        src: values-secret.yaml.j2
        dest: ~/values-secret.yaml

    - name: Ensure helm is installed
      ansible.builtin.unarchive:
        src: "https://get.helm.sh/helm-v3.9.2-linux-amd64.tar.gz"
        dest: /tmp
        remote_src: true

    - name: Install kubernetes Python module 
      ansible.builtin.pip:
        name: kubernetes
      become: true

    - name: Install helm in PATH
      ansible.builtin.copy:
        src: /tmp/linux-amd64/helm
        dest: /usr/bin/
        remote_src: true
        mode: +x
      become: true

    - name: Cleanup temp folder
      ansible.builtin.file:
        state: absent
        path: /tmp/linux-amd64/
      
    - name: Ensure right packages are in place
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: latest
      become: true
      loop:
        - make
    
    - name: Run make show command to validate output
      community.general.make:
        chdir: ~/industrial-edge
        target: show

    - name: Run install target to setup the environment
      community.general.make:
        chdir: ~/industrial-edge
        target: install

    - name: Log in (obtain access token)
      community.okd.openshift_auth:
        username: "{{ ocp_username }}"
        password: "{{ ocp_password }}"
        host: "{{ ocp_api_url }}"
        verify_ssl: false
      register: openshift_auth_results

    - name: Obtain routes for ArgoCD from the cluster
      kubernetes.core.k8s_info:
        api_version: route.openshift.io/v1
        kind: Route
        name: "{{ item.route_name }}"
        namespace: "{{ item.namespace }}"
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
        host: "{{ ocp_api_url }}"
        verify_ssl: false
      loop: "{{ ocp_resources }}"
      register: routes

    - name: Obtain admin password for ArgoCD from the cluster
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Secret
        name: "{{ item.secret_name }}"
        namespace: "{{ item.namespace }}"
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
        host: "{{ ocp_api_url }}"
        verify_ssl: false
      loop: "{{ ocp_resources }}"
      register: secrets

    - name: Print objects
      ansible.builtin.debug:
        msg: | 
          Host address for ArgoCD in {{ item.namespace }} is: {{ routes | community.general.json_query(route_query) | select() | join() }}
          Password for ArgoCD instance in {{ item.namespace }} namespace is: {{ secrets | community.general.json_query(secret_query) | select() | join() | b64decode }}
      vars:
        route_query: "results[*].resources[?metadata.name=='{{ item.route_name }}'].spec.host"
        secret_query: "results[*].resources[?metadata.name=='{{ item.secret_name }}'].data.\"admin.password\""
      loop: "{{ ocp_resources }}"
